# Generated by Django 3.0.5 on 2020-04-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('oponent1', models.CharField(choices=[('DQL', 'DQL'), ('PPO', 'PPO'), ('A2C', 'A2C'), ('AIRL', 'AIRL'), ('RANDOM', 'RAN')], default='RANDOM', max_length=6)),
                ('oponent2', models.CharField(choices=[('DQL', 'DQL'), ('PPO', 'PPO'), ('A2C', 'A2C'), ('AIRL', 'AIRL'), ('RANDOM', 'RAN')], default='RANDOM', max_length=6)),
                ('oponent3', models.CharField(choices=[('DQL', 'DQL'), ('PPO', 'PPO'), ('A2C', 'A2C'), ('AIRL', 'AIRL'), ('RANDOM', 'RAN')], default='RANDOM', max_length=6)),
                ('previousGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SingleGame.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SingleGame.User')),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('gameNumber', models.IntegerField(default=0)),
                ('roundNumber', models.IntegerField(default=0)),
                ('player', models.IntegerField(default=0)),
                ('actionType', models.CharField(max_length=50)),
                ('playerHand', models.CharField(max_length=400)),
                ('board', models.CharField(max_length=400)),
                ('possibleActions', models.CharField(max_length=400)),
                ('cardAction', models.CharField(max_length=400)),
                ('loss', models.CharField(max_length=400)),
                ('wrongActions', models.CharField(max_length=400)),
                ('totalActions', models.CharField(max_length=400)),
                ('scores', models.CharField(max_length=400)),
                ('roles', models.CharField(max_length=400)),
                ('playerStatus', models.CharField(max_length=400)),
                ('agentNames', models.CharField(max_length=400)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SingleGame.Game')),
            ],
        ),
    ]
