# Generated by Django 3.0.5 on 2020-04-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SingleGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='previousGame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SingleGame.Game'),
        ),
    ]
