# Generated by Django 3.0.5 on 2020-04-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingleGame', '0002_auto_20200419_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='gameNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='actions',
            name='player',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='actions',
            name='roundNumber',
            field=models.CharField(max_length=50),
        ),
    ]
