# Generated by Django 3.0.5 on 2020-04-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingleGame', '0003_auto_20200419_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='qValues',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='actions',
            name='reward',
            field=models.CharField(default='', max_length=400),
        ),
    ]
