# Generated by Django 3.0.5 on 2021-01-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingleGame', '0004_auto_20200419_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expName', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now=True)),
                ('gameNumber', models.IntegerField()),
                ('roundNumber', models.IntegerField()),
                ('player', models.IntegerField()),
                ('actionType', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='previousGame',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
