# Generated by Django 3.0.5 on 2021-01-07 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingleGame', '0006_dataset_playerhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='Qvalues',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='agentNames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='cardsAction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='loss',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dataset',
            name='performanceScore',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='playerStatus',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=10), size=None), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='possibleActions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='reward',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dataset',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='totalActions',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dataset',
            name='wrongActions',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='gameNumber',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='player',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='playerHand',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=list), size=None), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='roundNumber',
            field=models.CharField(default='', max_length=4),
        ),
    ]
