# Generated by Django 3.0.5 on 2021-01-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SingleGame', '0008_auto_20210107_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='expName',
            new_name='experiment',
        ),
    ]
