# Generated by Django 3.0.5 on 2021-01-07 17:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingleGame', '0013_auto_20210107_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='cardsAction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None),
        ),
    ]
