# Generated by Django 3.0.5 on 2021-01-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingleGame', '0014_auto_20210107_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('nickName', models.CharField(default='', max_length=500)),
                ('score', models.FloatField(blank=True)),
            ],
        ),
    ]
