# Generated by Django 3.0.5 on 2021-01-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingleGame', '0015_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='roundNumber',
            field=models.IntegerField(),
        ),
    ]
